<form action="<?php echo generateUrl(array('page'=>'process_login'));?>" method="POST">
    <label for="first_name">Your login: </label><input type="text" id="first_name" name="login" placeholder="Past Login"><br>
    <label for="password">Your password: </label><input type="password" id="password" name="password" password="password"><br>
    <input type="submit" name="submit" value="To send">
</form>