<form action="<?php echo generateUrl(array('page'=>'process_registration'));?>" method="POST">
    <label for="first_name">Your email: </label><input type="text" id="first_name" name="email" placeholder="Past Email"><br>
    <label for="password">Your password: </label><input type="password" id="password" password="password"><br>
    <input type="checkbox" value="1" name="remember">Remember<br>
    Female: <input type="radio" value="male" name="sex">Man | <input type="radio" value="female" name="sex"> Woman <br>
    <textarea name="comments" rows="5" cols="40"></textarea><br>
    <input type="submit" name="submit" value="To send">
</form>
